#!/bin/sh

set -e

case "$1" in
    configure|upgrade|update|reconfigure)
      # To read from logdir it needs the x flag
      LOGDIR='/var/log/nordvpn'
      if [ -d "$LOGDIR" ]; then
          chmod +x "$LOGDIR"
      fi
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    triggered)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
